language: python
python:
- 3.6
before_install:
- touch .env
- git fetch origin master
- 'if [ $TRAVIS_PULL_REQUEST != "false" ]; then git show FETCH_HEAD:devbot/__init__.py > CURRENT_VERSION; fi'
install:
- pipenv sync --dev
script:
- pipenv run black --check devbot
- pipenv run pylint devbot
- 'if [ $TRAVIS_PULL_REQUEST != "false" ]; then diff -sq CURRENT_VERSION devbot/__init__.py; if [[ $? -eq 0 ]]; then exit 1; fi; exit 0; fi;'
